---

- name: establish packages
  become: yes
  package:
    name: 
      - git
      - "{{ flavor }}"
    state: present
  tags: install

- name: ensure config path presence
  file:
    path: "{{ flavor_info[flavor]['config']['path'] }}"
    state: directory
  tags: install

- name: establish editor configuration 
  template:
    src: vimrc.j2
    dest: "{{ flavor_info[flavor]['config']['file'] }}"
  register: vimrc
  tags: configure

- name: establish plugin manager
  when: plugin_manager in plugin_manager_repo 
  git:
    repo: "{{ plugin_manager_repo[plugin_manager] }}"
    dest: "{{ flavor_info[flavor]['config']['path'] }}/bundle/{{ plugin_manager }}"
    update: yes
  tags: configure

- name: load plugins
  when: vimrc.changed
  shell: "{{ flavor_info[flavor]['command'] }} +PluginInstall +qall"
  tags: configure

- include_tasks: plugins.yml
  when: vimrc.changed
  tags: configure

