---

- name: establish packages
  become: "{{ (ansible_system == 'Linux') | bool }}"
  package:
    name:
      - git
      - "{{ vim_flavor }}"
    state: present
  tags: install

- name: ensure config path presence
  file:
    path: "{{ vim_flavor_info[vim_flavor]['config']['path'] }}"
    state: directory
  tags: install

- name: establish editor configuration
  copy:
    content: |
      " WARNING: This file is generated and managed by Ansible
      "

      {{ vim_configuration }}
    dest: "{{ vim_flavor_info[vim_flavor]['config']['file'] }}"
  register: vimrc
  tags: configure

- name: establish plugin manager   # noqa 401
  when: vim_plugin_manager in vim_plugin_manager_repo
  git:
    repo: "{{ vim_plugin_manager_repo[vim_plugin_manager] }}"
    dest: "{{ vim_flavor_info[vim_flavor]['config']['path'] }}/bundle/{{ vim_plugin_manager }}"
    update: true
  tags: configure

- when: vimrc.changed
  include_tasks: prepare_plugins.yml
  tags: configure
