---

- name: establish dependencies
  become: yes
  package:
    name:
      - cmake
      - python3-dev
    state: present
  tags: install

- set_fact:
    plugin_list: "{{ plugins | map(attribute='name') | list }}"
  tags: configure

- when: "'Valloric/YouCompleteMe' in plugin_list"
  block:
    - name: load repo
      shell: "git submodule update --init --recursive"
      args: 
        chdir: "{{ flavor_info[flavor]['config']['path'] }}/bundle/YouCompleteMe/"
        creates: "{{ flavor_info[flavor]['config']['path'] }}/bundle/YouCompleteMe/third_party/ycmd/build.py"

    - name: setup YouCompleteMe
      shell: python3 install.py --clang-completer
      args:
        chdir: "{{ flavor_info[flavor]['config']['path'] }}/bundle/YouCompleteMe/"
  tags: configure

- name: setup Syntastic
  when: "'vim-syntastic/syntastic' in plugin_list"
  become: yes
  package:
    name: 
      - pylint
      - pylint3
      - shellcheck
    state: present 
  tags: configure
