---

- name: establish dependencies
  become: "{{ (ansible_system == 'Linux') | bool }}"
  vars:
    packages: "{{ (ansible_system == 'Darwin') | ternary(['cmake'],['cmake','python3-dev']) }}"
  package:
    name: "{{ packages }}"
    state: present
  tags: install

- name: establish plugins   # noqa 401
  git:
    repo: "https://github.com/{{ item }}"
    dest: "{{ vim_flavor_info[vim_flavor]['config']['path'] }}/bundle/{{ item | basename }}"
  loop: "{{ vim_configuration | regex_findall(\"'([\\w_\\-.]+/[\\w_\\-.]+)'\") | unique }}"
  register: loaded_vim_plugins
  tags: configure

- name: prepare new plugin facts
  set_fact:
    new_vim_plugins: "{{ loaded_vim_plugins['results'] | selectattr('changed') | map(attribute='item') | list }}"
  tags: always

- name: setup YouCompleteMe     # noqa 301
  when: "'Valloric/YouCompleteMe' in new_vim_plugins"
  command: python3 install.py --clang-completer
  args:
    chdir: "{{ vim_flavor_info[vim_flavor]['config']['path'] }}/bundle/YouCompleteMe/"
  tags: configure

- name: setup Syntastic
  when: "'vim-syntastic/syntastic' in new_vim_plugins"
  become: true
  package:
    name:
      - pylint
      - pylint3
      - shellcheck
      - yamllint
    state: present
  tags: configure
