---

- name: establish dependencies
  become: true
  package:
    name:
      - cmake
      - python3-dev
    state: present
  tags: install

- name: establish plugins   # noqa 401
  git:
    repo: "https://github.com/{{ item }}"
    dest: "{{ flavor_info[flavor]['config']['path'] }}/bundle/{{ item | basename }}"
  loop: "{{ plugins | map(attribute='name') | list }}"
  register: loaded_plugins
  tags: configure

- name: prepare new plugin facts
  set_fact:
    new_plugins: "{{ loaded_plugins['results'] | selectattr('changed') | map(attribute='item') | list }}"
  tags: always

- name: setup YouCompleteMe     # noqa 301
  when: "'Valloric/YouCompleteMe' in new_plugins"
  command: python3 install.py --clang-completer
  args:
    chdir: "{{ flavor_info[flavor]['config']['path'] }}/bundle/YouCompleteMe/"
  tags: configure

- name: setup Syntastic
  when: "'vim-syntastic/syntastic' in new_plugins"
  become: true
  package:
    name:
      - pylint
      - pylint3
      - shellcheck
      - yamllint
    state: present
  tags: configure
