---

- name: Converge
  hosts: all
  roles:
    - role: vim
      vars:
        vim_configuration:
          - name: configuration block title
            block: |
              set clipboard=unnamed
              set backspace=indent,eol,start
        vim_plugin_manager: vundle
        vim_plugins:
          - name: 'vim-scripts/vim-auto-save'
            settings: |
              let g:auto_save=1
              let g:auto_save_in_insert_mode=0
              let g:auto_save_no_updatetime=5
